### ISSUE TITLE
Dependency import

### ISSUE THREAD

**Issue by zhouyan** [JuliaIO/ProtoBuf.jl#110] opened 2018-07-09 14:00 UTC
In master after recent changes dependencies are now imported with `Main` prefix. Is there’s a particular rational behind this? If I understand correctly this essentially force the dependency to be first imported in Main before it can be included in other modules. If a generated module is never used in Main but only included in other user written modules, then it generate an error as the dependency module won’t be found in Main.

**Comment by tanmaykm** [comment] 2018-07-10 04:28
Yes, I did that during porting to 0.7, as the earlier notation does not work with 0.7 anymore. But I too realized soon later that it is not entirely correct. The issue with this is exactly what you described.

There seems to be a related issue caused by dropping of fully qualified module names [here](https://github.com/JuliaIO/ProtoBuf.jl/commit/dc096c99b418810cb09e31606bc07011d8bcf61a#diff-45cfbad7a9f588d2178d5e03a702a5c2R540) because of which nested modules are not resolved in certain cases.

Working out a fix for both right now.

**Comment by zhouyan** [comment] 2018-07-10 04:51
I see how the patch of fully qualified module can cause trouble in some cases. I don't have a good suggestion right now but will work on it as well. I think the root issue is that Julia does not have a global scope in the same sense as in some other language. For example, in C++ one can use `::namespace:nested_namespace::something` as an absolute path the resolve symbols while in Julia fully qualified name is not really fully qualified if it is nested.

**Closed** 2018-07-12 05:59 UTC
