### ISSUE TITLE
circular dependencies in message types

### ISSUE THREAD

**Issue by damiendr** [JuliaIO/ProtoBuf.jl#61] opened 2016-02-25 13:15 UTC
I'm trying to compile a .proto file that contains the following structure:

```
message A {
  ...
  repeated B xxx = 9;
}
message B {
  ...
  optional A yyy = 4;
}
```

This fails with the following error:

```
--julia_out: All types could not be fully resolved:
mymessages.A depends on mymessages.B
mymessages.B depends on mymessages.A
```

Everything compiles fine with `--cpp_out`.

**Comment by damiendr** [comment] 2016-02-25 13:51
Note: it seems that the problem will sooner or later involve a Julia language issue: https://github.com/JuliaLang/julia/issues/269

**Comment by BugDiver** [comment] 2016-07-17 10:09
@damiendr  +1

**Comment by bar4ka** [comment] 2016-09-01 17:40
Tried to use this on a real world scenario: https://github.com/bar4ka/POGOProtos
Compiled to end without errors but unusable at runtime with LoadError: LoadError: UndefVarError: 
Circular dependencies between modules are the cause

**Comment by tanmaykm** [comment] 2018-01-22 10:40
fixed by #100

**Closed by tanmaykm** 2018-01-22 10:40 UTC
